- name: docker build and push
  hosts: localhost

  tasks:
    - name: Build Docker Image
      command: docker build -t calculator.jar .
      args:
        chdir: /Users/yash/.jenkins/workspace/CICD

    - name: tag image
      command: docker tag calculator.jar yashrtalele/calculator:latest 

    - name: Log in to Docker Hub
      community.docker.docker_login:
        registry_url: https://index.docker.io/v1/
        username: yashrtalele
        password: Y97^5Samaiyra*

    - name: Push image
      command: docker push yashrtalele/calculator:latest

    - name: Run container
      command: docker run -d --name calculator -p 8081:8080 yashrtalele/calculator:latest
